kind: pipeline
name: default

steps:
- name: test
  image: python:3.7
  commands:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -e .[all]
    - ./run-tests.sh

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
      - coverage.xml
      - .coverage
  when:
    event:
      - push

- name: pypi
  image: plugins/pypi
  settings:
    username:
      from_secret: pypi_user
    password:
      from_secret: pypi_pass
    repository: https://upload.pypi.org/legacy/
    distributions:
      - sdist
  when:
    event:
      - tag

